# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU ${{ matrix.arduino-boards-fqbn }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arduino-boards-fqbn:
          - esp32:esp32:esp32s3:CDCOnBoot=cdc
          - esp32:esp32:esp32

        include:
          - arduino-boards-fqbn: esp32:esp32:esp32s3:CDCOnBoot=cdc
            sketch-names: autopilot-core.ino
            arduino-platform: esp32:esp32@3.1.1
            platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            required-libraries: TinyGPSPlus@1.0.3,QMC5883LCompass@1.2.3
            sketch-names-find-start: autopilot-core*
            extra-arduino-cli-args: "--warnings default --build-property compiler.libraries.ldflags=-Wl,--allow-multiple-definition "
            set-build-path: true

          - arduino-boards-fqbn: esp32:esp32:esp32
            sketch-names: autopilot.ino
            arduino-platform: esp32:esp32@3.1.1
            platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            required-libraries: TinyGPSPlus@1.0.3,TFT_eSPI@2.5.43,XPT2046_Touchscreen@1.4
            sketch-names-find-start: autopilot*
            extra-arduino-cli-args: "--warnings default --build-property compiler.libraries.ldflags=-Wl,--allow-multiple-definition "
            set-build-path: true

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          arduino-platform: ${{ matrix.arduino-platform }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ matrix.required-libraries }}
          sketch-names: ${{ matrix.sketch-names }}
          sketch-names-find-start: ${{ matrix.sketch-names-find-start }}
          extra-arduino-cli-args: ${{ matrix.extra-arduino-cli-args }}
          set-build-path: ${{ matrix.set-build-path }}

      - name: Find versions
        run: |
          find /home/runner -name esptool\*
          find /home/runner -name boot_app0.bin
          ls -la /home/runner/
          ls -l /home/runner/.arduino15/packages/esp32/tools/esptool_py/*
